import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { LibrarianAuthProvider } from "@/Providers/AuthLibrarian";
import { BookProvider } from "@/Providers/ManageBooks";
import {GenreProvider} from "@/Providers/ManageGenres"
import { MemberProvider } from "@/Providers/ManageMembers";
import { TransactionProvider } from "@/Providers/ManageTransactions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <LibrarianAuthProvider>
      <MemberProvider>
        <TransactionProvider>
          <BookProvider>
            <GenreProvider>
                <html lang="en">
                  <body className={inter.className}>{children}</body>
                </html>
            </GenreProvider>
          </BookProvider>
        </TransactionProvider>
      </MemberProvider>
    </LibrarianAuthProvider>
  );
}
